theme: darkly
title: Sit3 under construction XD Welcome to my page :D
permalink: /_posts/:title/
description: >- # this means to ignore newlines until "baseurl:"
  Feel free to visit my page for sharing session. xD
#baseurl: "/faisalfs10x" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  faisalfs10x
error_message: >-
  Whatcha doing??
# github:
#   repository_url: http://www.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: faisalfs10x
